/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountPassword: typeof import('./../src/components/LoginDialog/components/FormLogin/AccountPassword.vue')['default']
    ConfirmDialog: typeof import('./../src/components/system/ConfirmDialog/index.vue')['default']
    ConversationListSkeleton: typeof import('./../src/components/skeleton/ConversationListSkeleton.vue')['default']
    DeepThinking: typeof import('./../src/components/DeepThinking/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ErrorBoundary: typeof import('./../src/components/system/ErrorBoundary/index.vue')['default']
    FabButton: typeof import('./../src/components/system/FabButton/index.vue')['default']
    FilesSelect: typeof import('./../src/components/FilesSelect/index.vue')['default']
    IconSelect: typeof import('./../src/components/IconSelect/index.vue')['default']
    Index_20260808_131048_967: typeof import('./../src/components/ModelSelect/index_20260808_131048_967.vue')['default']
    LoginDialog: typeof import('./../src/components/LoginDialog/index.vue')['default']
    MessageListSkeleton: typeof import('./../src/components/skeleton/MessageListSkeleton.vue')['default']
    ModelParametersPanel: typeof import('./../src/components/ModelParametersPanel/index.vue')['default']
    ModelSelect: typeof import('./../src/components/ModelSelect/index.vue')['default']
    NetworkStatusBar: typeof import('./../src/components/system/NetworkStatusBar/index.vue')['default']
    NoAttachmentsEmpty: typeof import('./../src/components/empty/NoAttachmentsEmpty.vue')['default']
    NoConversationsEmpty: typeof import('./../src/components/empty/NoConversationsEmpty.vue')['default']
    NoSearchResultsEmpty: typeof import('./../src/components/empty/NoSearchResultsEmpty.vue')['default']
    Popover: typeof import('./../src/components/Popover/index.vue')['default']
    QrCodeLogin: typeof import('./../src/components/LoginDialog/components/QrCodeLogin/index.vue')['default']
    RegistrationForm: typeof import('./../src/components/LoginDialog/components/FormLogin/RegistrationForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsSkeleton: typeof import('./../src/components/skeleton/SettingsSkeleton.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    TabBar: typeof import('./../src/components/system/TabBar/index.vue')['default']
    ToastContainer: typeof import('./../src/components/system/ToastContainer/index.vue')['default']
    TokenUsageBar: typeof import('./../src/components/TokenUsageBar/index.vue')['default']
    TopBar: typeof import('./../src/components/system/TopBar/index.vue')['default']
    VerificationCode: typeof import('./../src/components/LoginDialog/components/FormLogin/VerificationCode.vue')['default']
    WelecomeText: typeof import('./../src/components/WelecomeText/index.vue')['default']
    WorkspaceSwitcher: typeof import('./../src/components/WorkspaceSwitcher/index.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
