/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppRail: typeof import('./components/chat/AppRail.vue')['default']
    AssistantSettings: typeof import('./components/chat/AssistantSettings.vue')['default']
    ChatComposer: typeof import('./components/chat/ChatComposer.vue')['default']
    ChatInspector: typeof import('./components/chat/ChatInspector.vue')['default']
    ChatMessages: typeof import('./components/chat/ChatMessages.vue')['default']
    ChatSidebar: typeof import('./components/chat/ChatSidebar.vue')['default']
    ChatTopbar: typeof import('./components/chat/ChatTopbar.vue')['default']
    CommandPalette: typeof import('./components/chat/CommandPalette.vue')['default']
    DataManager: typeof import('./components/settings/DataManager.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ModelSelector: typeof import('./components/chat/ModelSelector.vue')['default']
    PromptEditor: typeof import('./components/chat/PromptEditor.vue')['default']
    ProviderSettings: typeof import('./components/chat/ProviderSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    S3Settings: typeof import('./components/settings/S3Settings.vue')['default']
    SearchView: typeof import('./components/chat/SearchView.vue')['default']
    SettingsPanel: typeof import('./components/chat/SettingsPanel.vue')['default']
    SettingsView: typeof import('./components/chat/SettingsView.vue')['default']
    StorageSettings: typeof import('./components/settings/StorageSettings.vue')['default']
    SyncPanel: typeof import('./components/settings/SyncPanel.vue')['default']
    ThinkingChain: typeof import('./components/chat/ThinkingChain.vue')['default']
    ToastNotification: typeof import('./components/chat/ToastNotification.vue')['default']
    WebDAVSettings: typeof import('./components/settings/WebDAVSettings.vue')['default']
    WelcomeScreen: typeof import('./components/chat/WelcomeScreen.vue')['default']
  }
}
