/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssistantSettings: typeof import('./components/chat/AssistantSettings.vue')['default']
    ChatAttachments: typeof import('./components/chat/ChatAttachments.vue')['default']
    ChatComposer: typeof import('./components/chat/ChatComposer.vue')['default']
    ChatInspector: typeof import('./components/chat/ChatInspector.vue')['default']
    ChatMessages: typeof import('./components/chat/ChatMessages.vue')['default']
    ChatSidebar: typeof import('./components/chat/ChatSidebar.vue')['default']
    ChatTopbar: typeof import('./components/chat/ChatTopbar.vue')['default']
    CommandPalette: typeof import('./components/chat/CommandPalette.vue')['default']
    ModelSelector: typeof import('./components/chat/ModelSelector.vue')['default']
    PromptEditor: typeof import('./components/chat/PromptEditor.vue')['default']
    ProviderSettings: typeof import('./components/chat/ProviderSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./components/chat/SettingsPanel.vue')['default']
    ThinkingChain: typeof import('./components/chat/ThinkingChain.vue')['default']
    ToastNotification: typeof import('./components/chat/ToastNotification.vue')['default']
    WelcomeScreen: typeof import('./components/chat/WelcomeScreen.vue')['default']
  }
}
